from collections.abc import Iterator

from sqlalchemy import MetaData, create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.config import settings

# Deterministic names for every constraint/index. Without this, autogenerated
# constraints are anonymous, and SQLite's batch mode (used to emulate ALTER in
# later migrations) cannot drop or recreate an unnamed constraint.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model.

    Alembic autogeneration compares this ``metadata`` against the live database,
    so every model must inherit from it to be seen by migrations.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# SQLite hands out one connection per thread by default and refuses to let a
# connection cross threads. FastAPI serves requests from a thread pool, so we
# relax that check for SQLite only. PostgreSQL (module 4+) needs no such flag.
_connect_args = {"check_same_thread": False} if settings.database_url.startswith("sqlite") else {}

engine = create_engine(settings.database_url, connect_args=_connect_args)

# autoflush/autocommit off: the *service* layer owns transaction boundaries,
# so nothing is written until a service calls commit().
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


def get_session() -> Iterator[Session]:
    """FastAPI dependency yielding a session that is always closed afterwards."""
    session = SessionLocal()
    try:
        yield session
    finally:
        session.close()
